version: "3.5"

services:
  dev_env_cache:
    container_name: dev_env_cache
    image: bitnami/redis:latest
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=CC_4932
    restart: always
    networks:
      - dev_env_video
  dev_env_apis:
    build: .
    volumes:
      - /usr/src/app/node_modules
      - ./:/usr/src/app
    ports:
      - 8080:8080
    environment:
      - SERVER_PORT=8080
      - NODE_ENV=DEVELOPMENT
    container_name: dev_env_apis
    restart: always
    networks:
      - dev_env_video
    depends_on:
      - dev_env_cache
    command: npm run start
  dev_env_wkr_user:
    build: .
    volumes:
      - /usr/src/app/node_modules
      - ./:/usr/src/app
    ports:
      - 3009:8081
    environment:
      - SERVER_PORT=8080
      - NODE_ENV=DEVELOPMENT
    container_name: dev_env_wkr_user
    restart: always
    networks:
      - dev_env_video
    depends_on:
      - dev_env_apis
    command: npm run user
  dev_env_wkr_video:
    build: .
    volumes:
      - /usr/src/app/node_modules
      - ./:/usr/src/app
    ports:
      - 3008:8081
    environment:
      - SERVER_PORT=8080
      - NODE_ENV=DEVELOPMENT
    container_name: dev_env_wkr_video
    restart: always
    networks:
      - dev_env_video
    depends_on:
      - dev_env_apis
    command: npm run video

networks:
  dev_env_video:
    name: dev_env_video
